/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\eight_ball.glb 
Author: RoutineStudio (https://sketchfab.com/TheRoutine)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/eight-ball-24a32adaf6014528ad71a1de9af6b084
Title: Eight Ball
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function EightBall(props) {
  const { nodes, materials } = useGLTF('/models/eight_ball.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Billard_Ball_Front_Side_0.geometry} material={materials.Front_Side} />
      <mesh geometry={nodes.Billard_Ball_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.Billard_Ball_Back_Side_0.geometry} material={materials.Back_Side} />
    </group>
  )
}

useGLTF.preload('/models/eight_ball.glb')
