/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\hero_model.glb -T 
Files: .\hero_model.glb [7.23MB] > C:\webdev\portfolio_2025\public\models\hero_model-transformed.glb [906.42KB] (87%)
Author: abdullahdlpr (https://sketchfab.com/abdullahdlpr)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/programmer-desktop-3d-pc-b22983c256174878973cf59b11e90aad
Title: Programmer desktop 3d PC
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { Environment } from "@react-three/drei";


export function HeroModel(props) {
  const { nodes, materials } = useGLTF('/models/hero_model-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <Environment preset="warehouse" background={false} />
      <mesh castShadow
        receiveShadow geometry={nodes.Cube011_Material010_0.geometry} material={materials['Material.074']} position={[3.537, 1.997, -0.859]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[1.735, 0.9, 1.573]} />
      <mesh castShadow
        receiveShadow geometry={nodes.Cube_Material_0.geometry} material={materials.Material} position={[-1.561, -0.006, -0.61]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-3.689, 7.316, 0.26]} />
      <mesh castShadow
        receiveShadow geometry={nodes.Cylinder_Material009_0.geometry} material={materials.PaletteMaterial001} position={[2.629, 0.512, 0.742]} rotation={[0, -Math.PI / 2, 0]} scale={[0.061, 0.063, 0.023]} />
      <mesh castShadow
        receiveShadow geometry={nodes.aorus_case_fans_aorus_case_fans_0.geometry} material={materials['Material.074_0']} position={[3.554, 2.887, 0.896]} scale={1.085} />
      <mesh castShadow
        receiveShadow geometry={nodes.Cube015_Material016_0.geometry} material={materials['Material.074_1']} position={[4.408, 2.241, -1.655]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-0.894, 0.007, 1.064]} />
      <mesh castShadow
        receiveShadow geometry={nodes.Cube020_Material020_0.geometry} material={materials['Material.074_2']} position={[3.634, 0.788, -0.961]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[1.607, 0.739, 0.343]} />
      <mesh castShadow
        receiveShadow geometry={nodes.IOSHIELD_IOSHIELD_0.geometry} material={materials['Material.074_3']} position={[4.225, 2.848, -2.597]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={[0.265, 0.309, 0.318]} />
      <mesh castShadow
        receiveShadow geometry={nodes.MOBOAORUSORANGETRANS_MOBOAORUSORANGETRANS_0.geometry} material={materials['Material.074_4']} position={[4.239, 2.877, -2.356]} rotation={[-0.651, -Math.PI / 2, 0]} scale={0.063} />
      <mesh castShadow
        receiveShadow geometry={nodes.Cube025_Material023_0.geometry} material={materials['Material.023']} position={[4.408, 2.241, -1.655]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-0.894, 0.007, 1.064]} />
      <mesh castShadow
        receiveShadow geometry={nodes.Cube026_Material024_0.geometry} material={materials['Material.024']} position={[4.408, 2.241, -1.655]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-0.894, 0.007, 1.064]} />
      <mesh castShadow
        receiveShadow geometry={nodes['metal-mesh-500x500_metal-mesh-500x500_0'].geometry} material={materials['Material.074_5']} position={[3.542, 3.57, -0.423]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1, 1.337, 1]} />
      <mesh castShadow
        receiveShadow geometry={nodes.Cube027_Material008_0.geometry} material={materials['Material.074_6']} position={[4.309, 2.71, -0.964]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.015, 0.109, 0.443]} />
      <mesh castShadow
        receiveShadow geometry={nodes.Cube028_Material026_0.geometry} material={materials['Material.074_7']} position={[4.324, 2.71, -0.957]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.011, 0.097, 0.444]} />
      <mesh castShadow
        receiveShadow geometry={nodes.Cube045_Material027_0.geometry} material={materials['Material.074_8']} position={[2.982, 0.794, -2.121]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.355, 0.052, 0.206]} />
      <mesh castShadow
        receiveShadow geometry={nodes['rgb-hdd-cover-aorus-v1_rgb-hdd-cover-aorus-v1_0'].geometry} material={materials['Material.074_9']} position={[2.888, 0.832, -0.935]} rotation={[0, -Math.PI / 2, 0]} scale={0.369} />
      <mesh castShadow
        receiveShadow geometry={nodes['maxresdefault_(1)_maxresdefault_(1)_0'].geometry} material={materials['Material.074_10']} position={[3.553, 0.836, 0.877]} scale={0.394} />
      <mesh castShadow
        receiveShadow geometry={nodes.Cylinder001_Material028_0.geometry} material={materials['Material.074_11']} position={[0.716, 1.144, -1.692]} rotation={[-0.017, 0, -Math.PI / 2]} scale={[0.194, 0.194, 0.025]} />
      <mesh castShadow
        receiveShadow geometry={nodes.NVIDIA_LOGO_NVIDIA_LOGO_0.geometry} material={materials['Material.074_12']} position={[2.891, 0.704, 0.006]} rotation={[0, -Math.PI / 2, 0]} scale={0.452} />
      <mesh castShadow
        receiveShadow geometry={nodes.psuback_psuback_0.geometry} material={materials['Material.074_13']} position={[3.528, 0.78, -2.603]} scale={0.595} />
      <mesh castShadow
        receiveShadow geometry={nodes.usb_usb_0.geometry} material={materials['Material.074_14']} position={[2.897, 3.571, 0.705]} rotation={[-Math.PI / 2, 0, 0]} scale={0.073} />
      <mesh castShadow
        receiveShadow geometry={nodes.Cube048_Material035_0.geometry} material={materials['Material.074_15']} position={[3.682, 2.682, -1.614]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.174, 0.394, 0.401]} />
      <mesh castShadow
        receiveShadow geometry={nodes.Cube049_Material040_0.geometry} material={materials['Material.074_16']} position={[3.682, 2.682, -1.614]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.174, 0.394, 0.401]} />
      <mesh castShadow
        receiveShadow geometry={nodes.Cylinder005_Material041_0.geometry} material={materials['Material.074_17']} position={[3.69, 2.687, -1.611]} rotation={[0, 0, -Math.PI / 2]} scale={[0.327, 0.327, 0.342]} />
      <mesh castShadow
        receiveShadow geometry={nodes['test-aorus-m2-souris-aorus-rgb2_test-aorus-m2-souris-aorus-rgb2_0'].geometry} material={materials['Material.074_18']} position={[4.352, 1.507, -1.159]} rotation={[0, -Math.PI / 2, 0]} scale={0.352} />
      <mesh castShadow
        receiveShadow geometry={nodes.Cylinder006_Material050_0.geometry} material={materials['Material.074_19']} position={[3.701, 1.846, -2.095]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.364, 0.382, 0.106]} />
      <mesh castShadow
        receiveShadow geometry={nodes.Cylinder007_Material051_0.geometry} material={materials['Material.074_20']} position={[3.701, 1.846, -1.244]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.364, 0.382, 0.106]} />
      <mesh castShadow
        receiveShadow geometry={nodes.Cube057_Material059_0.geometry} material={materials['Material.074_22']} position={[3.706, 2.001, -1.272]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[1.281, 0.524, 0.127]} />
      <mesh castShadow
        receiveShadow geometry={nodes.Cube058_Material063_0.geometry} material={materials['Material.074_23']} position={[3.704, 2.137, -1.226]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[1.333, 0.545, 0.008]} />
      <mesh castShadow
        receiveShadow geometry={nodes.aorus_logotranspa_aorus_logotranspa_0.geometry} material={materials['Material.074_24']} position={[3.158, 1.817, -1.824]} rotation={[0, -Math.PI / 2, 0]} scale={[0.086, 0.086, 0.091]} />
      <mesh castShadow
        receiveShadow geometry={nodes['Color-PewDiePie-Logo_Color-PewDiePie-Logo_0'].geometry} material={materials['Material.074_27']} position={[0.275, 0.466, 1.295]} rotation={[-1.287, 0, 0]} scale={0.124} />
      <mesh castShadow
        receiveShadow geometry={nodes.gallerymodel_gallerymodel_0.geometry} material={materials['Material.074_28']} position={[-5.961, 1.648, -1.42]} rotation={[3.016, -0.259, 3.125]} scale={0.807} />
      <mesh castShadow
        receiveShadow geometry={nodes.bg2_bg2_0.geometry} material={materials['Material.074_29']} position={[-0.83, 1.949, -1.537]} rotation={[3.012, 0, 3.136]} scale={1.13} />
      <mesh castShadow
        receiveShadow geometry={nodes.MY_SCREEN_MY_SCREEN_0.geometry} material={materials['Material.074_30']} position={[-3.004, 3.001, -1.362]} rotation={[-0.07, 0, 0]} scale={[3.316, 3.481, 3.316]} />
      <mesh castShadow
        receiveShadow geometry={nodes['gigabyte-logo_gigabyte-logo_0'].geometry} material={materials['Material.074_31']} position={[-0.821, 4.494, -1.615]} rotation={[3.072, 0, Math.PI]} scale={0.237} />
      <mesh castShadow
        receiveShadow geometry={nodes.Object_47_Material005_0.geometry} material={materials['Material.074_32']} position={[-4.031, 0.326, 1.477]} rotation={[-3.051, 0, 0]} scale={0.914} />
      <mesh castShadow
        receiveShadow geometry={nodes.Object_49_Tasten_2_0.geometry} material={materials.Tasten_2} position={[-4.031, 0.326, 1.477]} rotation={[-3.051, 0, 0]} scale={0.914} />
      <mesh castShadow
        receiveShadow geometry={nodes.Object_55_Material057_0.geometry} material={materials['Material.074_33']} position={[-4.031, 0.326, 1.477]} rotation={[-3.051, 0, 0]} scale={0.914} />
      <mesh castShadow
        receiveShadow geometry={nodes.Object_59_Material060_0.geometry} material={materials['Material.074_34']} position={[-4.031, 0.326, 1.477]} rotation={[-3.051, 0, 0]} scale={0.914} />
      <mesh castShadow
        receiveShadow geometry={nodes.Object_65_Material066_0.geometry} material={materials['Material.074_35']} position={[-4.031, 0.326, 1.477]} rotation={[-3.051, 0, 0]} scale={0.914} />
      <mesh castShadow
        receiveShadow geometry={nodes.Object_67_Material067_0.geometry} material={materials['Material.074_36']} position={[-4.031, 0.326, 1.477]} rotation={[-3.051, 0, 0]} scale={0.914} />
      <mesh castShadow
        receiveShadow geometry={nodes.Object_81_Material068_0.geometry} material={materials['Material.074_37']} position={[-4.031, 0.326, 1.477]} rotation={[-3.051, 0, 0]} scale={0.914} />
      <mesh castShadow
        receiveShadow geometry={nodes.Object_93_Material069_0.geometry} material={materials['Material.074_38']} position={[-4.031, 0.326, 1.477]} rotation={[-3.051, 0, 0]} scale={0.914} />
      <mesh castShadow
        receiveShadow geometry={nodes.Object_103_Material070_0.geometry} material={materials['Material.074_39']} position={[-4.031, 0.326, 1.477]} rotation={[-3.051, 0, 0]} scale={0.914} />
      <mesh castShadow
        receiveShadow geometry={nodes['Object_782_OnTheFly-bg_0'].geometry} material={materials['Material.074_40']} position={[-2.44, 0.406, 1.016]} rotation={[-1.493, 0, 0]} scale={0.219} />
    </group>
  )
}

useGLTF.preload('/models/hero_model-transformed.glb')
