/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\mountain_bike.glb 
Author: Kyler Michaelson (https://sketchfab.com/kylermichaelson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mountain-bike-cde6e3836f7a4ac19e361010fc49751e
Title: Mountain Bike
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function MountainBike(props) {
  const { nodes, materials } = useGLTF('/models/mountain_bike.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.LEAVES} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.flower_petal} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.grass_w_alpha} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.stem} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.wood} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.wood} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/mountain_bike.glb')
