/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\pool_ball.glb 
Author: Blender3D (https://sketchfab.com/Blender3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pool-ball-405f6ed74fa94dbd9a06629a334585db
Title: Pool Ball
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function PoolBall(props) {
  const { nodes, materials } = useGLTF('/models/pool_ball.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.None} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/pool_ball.glb')
